CREATE TABLE pet
(
    id                     BIGINT generated by default as identity primary key,
    pet_type               TEXT      NOT NULL,
    chat_id                BIGINT    NOT NULL REFERENCES users (user_chat_id)
);

CREATE TABLE client
(
    id                     BIGINT generated by default as identity primary key,
    name_client            TEXT      NOT NULL,
    phoneNumber            INT       NOT NULL,
    address                TEXT      NOT NULL,
    pet_set                TEXT      NOT NULL
);

CREATE TABLE shelter
(
    id                     BIGINT generated by default as identity primary key,
    name_shelter           TEXT      NOT NULL,
    address                TEXT      NOT NULL,
    schedule               INT       NOT NULL,
    about                  TEXT      NOT NULL,
    guard                  TEXT      NOT NULL,
    location_map           TEXT      NOT NULL,
    pet_type               TEXT      NOT NULL,
    volunteerSet           TEXT      NOT NULL,
    ownerSet               TEXT      NOT NULL
);

CREATE TABLE users
(
    id                     BIGINT generated by default as identity primary key,
    name_user              TEXT      NOT NULL,
    phoneNumber            INT       NOT NULL,
    shelter_id             INT       NOT NULL REFERENCES shelter (id),
    user_chat_id           BIGINT NOT NULL UNIQUE
);

CREATE TABLE volunteers
(
    id                     BIGINT generated by default as identity primary key,
    name_volunteer         TEXT      NOT NULL,
    chat_id                BIGINT    NOT NULL REFERENCES users (user_chat_id),
    available              BOOL      NOT NULL

);






