--liquibase formatted sql
--changeset kapkova:1

--CREATE TYPE pet_type AS ENUM ('CAT', 'DOG');


CREATE TABLE pet
(
    id                     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_type               pet_type  NOT NULL,
	   pet_name               VARCHAR   NOT NULL,
    availability           BOOLEAN
);

CREATE TABLE client
(
    id                     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_client            VARCHAR   NOT NULL,
    phone_number           VARCHAR   NOT NULL,
    address                TEXT      NOT NULL
);
-- Вспомогательная таблица для списка питомцев клиента

CREATE TABLE  pet_set_client
(
    client_id  BIGINT NOT NULL,
    pet_id     BIGINT NOT NULL,
    PRIMARY KEY (client_id, pet_id),
	CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES  client (id),
	CONSTRAINT fk_pet_id FOREIGN KEY (pet_id) REFERENCES  pet (id)
);

CREATE TABLE shelter
(
    id                     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_shelter           VARCHAR   NOT NULL,
    address                TEXT      NOT NULL,
    schedule               TEXT      NOT NULL,
    about                  TEXT      NOT NULL,
    guard                  TEXT      NOT NULL,
    location_map           TEXT      NOT NULL,
    pet_type               pet_type  NOT NULL

);

CREATE TABLE users
(
    id                     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_user              TEXT      NOT NULL,
    phoneNumber            INT       NOT NULL,
    shelter_id             INT       NOT NULL REFERENCES shelter (id),
    user_chat_id           BIGINT    NOT NULL UNIQUE
);


CREATE TABLE volunteers
(
    id                     BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_volunteer         VARCHAR   NOT NULL,
    chat_id                BIGINT    NOT NULL REFERENCES users (user_chat_id),
    available              BOOL      NOT NULL

);



CREATE TABLE  volunteer_set_shelter
(
    volunteers_id  BIGINT NOT NULL,
    shelter_id     BIGINT NOT NULL,
    PRIMARY KEY (volunteers_id, shelter_id),
	CONSTRAINT fk_volunteers_id FOREIGN KEY (volunteers_id) REFERENCES volunteers (id),
	CONSTRAINT fk_shelter_id FOREIGN KEY (shelter_id) REFERENCES  shelter (id)
);

CREATE TABLE  owner_set_shelter
(
    users_id  BIGINT NOT NULL,
    shelter_id     BIGINT NOT NULL,
    PRIMARY KEY (users_id, shelter_id),
	CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users (id),
	CONSTRAINT fk_shelter_id FOREIGN KEY (shelter_id) REFERENCES  shelter (id)
);

--CREATE TYPE menu AS ENUM ('GREETINGS', 'START', 'BACK', 'CHOOSE_CAT', 'CHOOSE_DOG', 'BASIC_INFO', 'TAKE_ANIMAL_HOME', 'SEND_ANIMAL_REPORT', 'CALL_VOLUNTEER');
--CREATE TYPE status AS ENUM ('SENDING_REPORT_PHOTO', 'SENDING_REPORT_TEXT', 'SENDING_REPORT_TEXT_AND_PHOTO');