CREATE TABLE pet
(
    id                     BIGINT generated by default as identity primary key,
    pet_type               TEXT      NOT NULL,
    chat_id                BIGINT    NOT NULL,
);

CREATE TABLE client
(
    id                     BIGINT generated by default as identity primary key,
    name                   TEXT      NOT NULL,
    phoneNumber            INT       NOT NULL,
    address                TEXT      NOT NULL,
    pet_set                TEXT      NOT NULL,
);

CREATE TABLE shelter
(
    id                     BIGINT generated by default as identity primary key,
    name                   TEXT      NOT NULL,
    address                TEXT      NOT NULL,
    schedule               INT       NOT NULL,
    about                  TEXT      NOT NULL,
    guard                  TEXT      NOT NULL,
    location_map           TEXT      NOT NULL,
    pet_type               TEXT      NOT NULL,
    volunteerSet           TEXT      NOT NULL,
    ownerSet               TEXT      NOT NULL,
);

CREATE TABLE users
(
    id                     BIGINT generated by default as identity primary key,
    name                   TEXT      NOT NULL,
    phoneNumber            INT       NOT NULL,
    shelter                TEXT      NOT NULL,
);

CREATE TABLE volunteers
(
    id                     BIGINT generated by default as identity primary key,
    name                   TEXT      NOT NULL,
    chat_id                BIGINT    NOT NULL,
    availability           BOOL      NOT NULL,

);






