CREATE TABLE IF NOT EXISTS pet
(
    id                     BIGINT generated by default as identity primary key,
    pet_type               integer,
    pet_name varchar,
    availability bool
);

CREATE TABLE IF NOT EXISTS client
(
    id                     BIGINT generated by default as identity primary key,
    name_client            varchar,
    phone_number           varchar,
    address                varchar,
    pet_id                 BIGINT REFERENCES pet (id),
    chat_id                BIGINT
);

CREATE TABLE IF NOT EXISTS volunteers
(
    id                     BIGINT generated by default as identity primary key,
    name_volunteer         varchar,
    chat_id                BIGINT,
    available              BOOL

);

CREATE TABLE IF NOT EXISTS report
(
    id                     BIGINT generated by default as identity primary key,
    chat_id_report         BIGINT,
    pet_name               varchar,
    health                 varchar,
    ration                 varchar,
    behaviour              varchar,
    message_date           timestamp,
    file_img               bytea
);

CREATE TABLE IF NOT EXISTS context
(
    chat_id      BIGSERIAL PRIMARY KEY,
    pet_type      INTEGER,
    client_id    BIGINT REFERENCES client (id)
);
